/* ═══ THE FOE DEX · one JSON of every enemy the game can field ════════════
   Derived, never authored (.claude/rules/enemy-stats.md): it runs every
   FOE_BUILD builder through the dev bench's own seeded catalogue, so a
   statblock change moves this file by itself. Its consumer is
   tools/enemies.html, regenerated by tools/dev/build_foedex.py.
   ⚠ The pts here are `unitPts`, the SAME scale the practice field prices
   both sides on (#216). It is a threat price, not a reward.                */
(()=>{
  const R=v=>Math.round(v*10)/10;
  const spriteOf=u=>{
    try{const s=sprite(u.kind,u.side||'foe',
      {unit:u,leader:u.leader||u.captain,caster:u.caster,bow:u.bow});
      return {src:s.src,w:s.w,h:s.h,key:s.key};}
    catch(e){return null;}
  };
  /* every fight, its whole cast in board order, with the same seed the
     bench uses so two calls never disagree */
  const casts={},kinds=Object.keys(FOE_BUILD);
  kinds.forEach(k=>{casts[k]=devFoeUnits(k);});

  /* one body, every field a table could want to show */
  const row=u=>{
    const t=(FOE_T[u._fight]||{})[u.variant]||null;
    /* ⛔ MOVE STAYS IN THE LIST. It was filtered out as furniture and it is not:
       it is one action for `speed` hexes, which is half of what a lurcher or a
       mirehare IS. `unitPts` filters it because it does no damage; a reader
       wants it. */
    const acts=(u.acts||[]).map(a=>({
      k:a.k,n:a.n,cost:a.cost||1,
      reach:a.reach||0,range:a.range||0,
      dmg:a.dmg?[a.dmg[0],a.dmg[1]]:null,
      am:a.am==null?null:a.am, ft:a.ft==null?null:a.ft,
      sweep:!!a.sweep,arcane:!!a.arcane,pull:a.pull||0,bounce:a.bounce||0,
      cool:a.cool||0,strain:a.strain||0,
      move:!!a.move, self:!!a.self,
      note:a.note||(typeof actNote==='function'?(actNote(a,u)||''):'')
    }));
    /* ⛔ #265 - A CHAMPION ROLLS TWO PERKS AND NOTHING ON A STATBLOCK SHOWS THEM.
       They are not acts, so an acts-only reading of a body misses half of what a
       champion is. `foePerks` writes them onto `u.perks`; `PERKS` has the words. */
    const perks=(u.perks||[]).map(k=>({k:k,
      n:(PERKS[k]||{}).n||k, d:(PERKS[k]||{}).d||''}));
    const best=acts.filter(a=>a.dmg&&!a.move).sort((a,b)=>
      (b.dmg[0]+b.dmg[1])-(a.dmg[0]+a.dmg[1]))[0]||null;
    const mon=u.monster&&MONSTERS[u.monster]?MONSTERS[u.monster]:null;
    return {
      variant:u.variant, name:u.name, kind:u.kind, race:u.race,
      monster:u.monster||'', tag:mon?mon.tag:'', nature:mon?mon.nature:'',
      pts:seededly(()=>unitPts(u)),
      hp:u.hpMax, armour:u.armourMax, soak:u.soak||0,
      mor:u.moraleMax, morOpen:u.morale0,
      hit:u.mskill, dodge:u.dodgeBase,
      speed:u.speed, actions:u.actionsMax,
      dmgBonus:u.dmgBonus||0, flankPow:u.flankPow||0, spellPow:u.spellPow||1,
      dmgLo:best?best.dmg[0]:0, dmgHi:best?best.dmg[1]:0,
      reach:Math.max.apply(null,[0].concat(acts.filter(a=>!a.move)
        .map(a=>Math.max(a.reach,a.range)))),
      perks:perks,
      /* ⛑ THE FAMILY IS DERIVED AND NEVER AUTHORED. A beast IS its bestiary row,
         which is the fact the game already keeps; everybody else belongs to the
         side that fields them, and the fight key is that side. `fam` is the key,
         `FAMILY` in the generator has the words. */
      fam:u.monster?('mon:'+u.monster):('fight:'+u._fight),
      st:u.st||null,
      flags:['captain','champ','caster','bow','big','bigkill','noRout','noArc',
             'fenborn','fireborn','veiled','flier','skittish','passive','noWalk',
             'noTrim','noFace','stands','fleet','unrepeatable']
        .filter(f=>u[f]),
      tailLen:u.tails?u.tails.length:(u.tail?1:0),
      guards:u.guards||'', aura:u.aura||'',
      bare:!!(t&&t.bare), lean:t&&t.lean?t.lean:null, authored:t?{
        hp:t.hp,armour:t.armour,mor:t.mor,skill:t.skill,dodge:t.dodge,speed:t.speed
      }:null,
      acts:acts, sprite:spriteOf(u), champ:!!u.champ
    };
  };

  /* dedupe exactly the way the bench does: same name at the same price is
     one body wearing two fights. Its `fights` list is what makes it two. */
  const out=[],by={};
  kinds.forEach(k=>{
    casts[k].forEach(u=>{
      u._fight=k;
      const pts=seededly(()=>unitPts(u));
      const key=u.name+'|'+pts;
      if(by[key]){ if(by[key].fights.indexOf(k)<0)by[key].fights.push(k); return; }
      const r=row(u); r.fights=[k]; by[key]=r; out.push(r);
    });
  });
  /* the fights themselves: what stands beside this body, and what the whole
     side is worth. This is the "typical party" column. */
  const fights={};
  kinds.forEach(k=>{
    const seen={},order=[];
    casts[k].forEach(u=>{
      /* ⛔ KEYED name+pts AND NEVER name ALONE. A champion wears its ordinary
         twin's name (Ash-drake 9 and 14, Hold corporal 9 and 13), so grouping
         by name folds two statblocks into one row and the card then prices the
         whole cast off whichever of them the sort happened to put first. It is
         the same key `by` uses above, for the same reason. */
      const pts=seededly(()=>unitPts(u)),key=u.name+'|'+pts;
      if(!seen[key]){seen[key]={n:0,name:u.name,variant:u.variant,pts:pts};order.push(key);}
      seen[key].n++;
    });
    let ally=[];
    try{ if(k==='clash')ally=clashAllies(); if(k==='snarejoin')ally=snareClan();
         if(k==='tavern')ally=build([[6,4,'barman',18]],TAVERN_T); }catch(e){}
    fights[k]={
      kind:k, bodies:casts[k].length,
      pts:casts[k].reduce((s,u)=>s+seededly(()=>unitPts(u)),0),
      allyPts:ally.reduce((s,u)=>s+seededly(()=>unitPts(u)),0),
      allies:ally.map(u=>u.name),
      cast:order.map(key=>seen[key])
    };
  });
  /* ⛑ WHICH CARD PUTS YOU IN THIS FIGHT, DERIVED OFF THE DECKS THEMSELVES.
     A door carries `battle:'<kind>'` already, so the road and the fire ARE the
     index; authoring a second list of "related events" beside the statblocks
     would be the promise-versus-payment shape this repo keeps deleting.
     ⚠ `battle:true` MEANS `snare`, which is `pickChoice`'s own line and not a
     guess - two of the Snare's four doors are written that way. */
  const cards={};
  const addCard=(k,src,title,door,danger)=>{
    if(k===true)k='snare';
    (cards[k]=cards[k]||[]).push({src:src,title:title,door:door,danger:!!danger});
  };
  const doorLabel=c=>{try{return (typeof evLabel==='function'?evLabel(c):c.c)||'';}
    catch(e){return '';}};
  [['road',EVENTS],['fire',CAMPS]].forEach(pair=>{
    Object.keys(pair[1]).forEach(k=>{const e=pair[1][k];
      (e.choices||[]).forEach(c=>{ if(!c.battle)return;
        addCard(c.battle,pair[0],e.title||k,c.t||doorLabel(c),c.danger);});});
  });
  Object.keys(fights).forEach(k=>{fights[k].cards=cards[k]||[];});

  /* ⛑ A CHAMPION IS LINKED TO THE BODY IT IS A BETTER VERSION OF, so the table
     can fold one under the other instead of printing near-twins side by side.
     The link is the VARIANT, which is what `CHAMP` multiplies: same variant,
     one carrying the word. #245's rule read as a join. */
  const baseOf={};
  out.forEach(f=>{if(!f.champ)baseOf[f.variant]=f.name+'|'+f.pts;});
  out.forEach(f=>{f.champOf=f.champ?(baseOf[f.variant]||null):null;});

  /* ⛑ WHAT ONE OF YOUR PEOPLE IS WORTH, DERIVED. The table prints a threat as a
     share of a starting body, and that divisor was a literal `10` for exactly as
     long as it took `PTS_SCALE` to move. `ARENA.COMPS.four()` IS the anchor the
     dial is calibrated against, so the tool reads the same thing the dial does. */
  const comps={};
  Object.keys(ARENA.COMPS).forEach(k=>{
    try{const c=ARENA.COMPS[k]();comps[k]={n:c.length,pts:seededly(()=>compPts(c))};}
    catch(e){}
  });
  return {built:new Date().toISOString().slice(0,10), foes:out, fights:fights,
          you:{hp:GIVEN.hp,hit:GIVEN.hit,dodge:GIVEN.dodge,nerve:GIVEN.nerve},
          comps:comps,
          scale:PTS_SCALE, hdaCut:typeof HDA_CUT!=='undefined'?HDA_CUT:1};
})()
