/* ═══ THE ARMOURY · one JSON of every artifact the game can hand you ══════
   The gear half of tools/dev/probes/foedex.js, and built to the same rule:
   DERIVED, NEVER AUTHORED. Every figure below is read off the running build -
   the row in GEAR{}, the price gearPrice() charges, the break-down scrapPay()
   pays, the painting ITEM_ICON points at - so a gear change moves this file by
   itself. Its consumer is tools/artifacts.html, regenerated by
   tools/dev/build_gear.py.

   ⛔ WHERE A THING COMES FROM IS SCANNED, NOT LISTED. The three decks and the
   loot tables ARE the index: a card carries `gear:'<key>'` on the door that
   hands it over, so walking the decks answers "how do I get this" without
   anybody authoring a second list beside the row. A list would be the
   promise-versus-payment shape this repo keeps deleting.
   ⚠ THE WALK IS DEEP AND NOT `choices[].gear`. A grant can sit under a nested
   object, and a one-level read would report it as unreachable - the worst
   possible lie for a census whose whole job is finding the unreachable.     */
(()=>{
  /* the structural fields: everything the table has a column for. Anything
     NOT in here is emitted verbatim as an effect, so a field written on a
     gear row next month shows up in this tool untaught. */
  const STRUCT={rarity:1,n:1,slot:1,size:1,d:1,g:1,unique:1,hands:1,
                dmg:1,am:1,ft:1,reach:1,range:1,act:1,throw:1,use:1,scrap:1};

  /* ── 1. where a key can come from ─────────────────────────────────────
     one deep walk per card, collecting every `gear:'<key>'` at any depth
     with the nearest door label above it. */
  const SRC={};
  const add=(k,o)=>{if(!k)return;(SRC[k]=SRC[k]||[]).push(o);};
  const walk=(node,label,seen,hit)=>{
    if(!node||typeof node!=='object')return;
    if(seen.indexOf(node)>=0)return; seen.push(node);
    const lab=(typeof node.t==='string'&&node.t)||label;
    if(typeof node.gear==='string')hit(node.gear,lab,node);
    Object.keys(node).forEach(f=>{
      const v=node[f];
      if(Array.isArray(v))v.forEach(x=>walk(x,lab,seen,hit));
      else if(v&&typeof v==='object')walk(v,lab,seen,hit);
    });
  };
  const scanDeck=(list,src)=>{
    list.forEach(pair=>{
      const id=pair[0],card=pair[1];
      const title=card.title||card.t||id;
      walk(card,'',[],(k,lab,node)=>add(k,{how:src,card:title,id:String(id),
        door:lab||'',pay:node.c||''}));
    });
  };
  scanDeck(Object.keys(EVENTS).map(k=>[k,EVENTS[k]]),'road');
  scanDeck(CAMPS.map((c,i)=>[c.id||('camp'+i),c]),'fire');
  scanDeck(VIGNETTES.map((v,i)=>['vig'+i,v]),'vignette');
  /* the loot tables are keyed by fight and their rows are flat */
  Object.keys(LOOT).forEach(kind=>{
    (LOOT[kind]||[]).forEach(r=>{if(r&&r.gear)
      add(r.gear,{how:'loot',card:kind,id:kind,door:r.t||'',pay:r.c||''});});
  });
  /* the four you start with, off a FRESH roster and never off G.party - the
     dev bench and a loaded save both write to that one */
  try{makeParty().forEach(p=>{
    Object.keys(p.eq||{}).forEach(sl=>{if(p.eq[sl])
      add(p.eq[sl],{how:'start',card:p.name,id:p.id,door:sl,pay:''});});});
  }catch(e){}
  (G.stash||[]).forEach(k=>add(k,{how:'start',card:'the cart',id:'stash',
    door:'in the wagon on day one',pay:''}));
  /* a hire arrives holding their trade's kit */
  Object.keys(START_GEAR).forEach(cls=>{
    (START_GEAR[cls]||[]).forEach((k,i)=>{if(k)
      add(k,{how:'hire',card:cls,id:cls,door:i?'in hand':'worn',pay:''});});});
  /* the named recruits the road can hand you */
  [typeof PRESET_SKREE!=='undefined'?PRESET_SKREE:null,
   typeof PRESET_ASH!=='undefined'?PRESET_ASH:null,
   typeof PRESET_BRUHT!=='undefined'?PRESET_BRUHT:null]
    .forEach(r=>{if(!r)return;
      Object.keys(r.eq||{}).forEach(sl=>{if(r.eq[sl])
        add(r.eq[sl],{how:'hire',card:r.name,id:r.id,door:sl,pay:''});});});
  /* the forge at the Old Camp: the one bench that MAKES a piece of kit */
  try{CRAFT.forEach(c=>add(c.k,{how:'forge',card:'the forge',id:'craft',
    door:c.n,pay:Object.keys(c.cost||{}).map(m=>c.cost[m]+' '+m).join(' + ')}));}
  catch(e){}

  /* ⛔ AND THE GRANTS THAT ARE NOT IN A TABLE AT ALL. Three keys are handed
     over by CODE - a card built at runtime (`cubChoice`), a `stashGain` inside
     a door's own handler, a body walked on wearing one - and a census that
     walks only the decks calls all three UNREACHABLE. That is the worst lie
     this tool can tell, because the whole point of the reach column is to name
     what nothing can reach. So every global function's own source is read.
     ⚠ COMMENTS ARE STRIPPED FIRST AND THIS IS NOT TIDINESS. `LINT`'s essay
     quotes `gear:'spear'` while explaining a check, and the first cut reported
     the linter as a place the road hands you a boar spear. A comment is not a
     grant, and `Function.prototype.toString` returns both. */
  const CODE={};
  (function(){
    const strip=s=>s.replace(/\/\*[\s\S]*?\*\//g,' ').replace(/(^|[^:])\/\/[^\n]*/g,'$1 ');
    const pats=[/gear\s*:\s*'([a-zA-Z0-9_]+)'/g,
                /stashGain\(\s*'([a-zA-Z0-9_]+)'\s*\)/g,
                /\.(?:trinket|main|off|armour)\s*=\s*'([a-zA-Z0-9_]+)'/g];
    Object.getOwnPropertyNames(window).forEach(nm=>{
      let f;try{f=window[nm];}catch(e){return;}
      if(typeof f!=='function')return;
      let s;try{s=Function.prototype.toString.call(f);}catch(e){return;}
      if(s.indexOf('[native code]')>=0)return;
      s=strip(s);
      pats.forEach(p=>{p.lastIndex=0;let m;
        while((m=p.exec(s))){if(!GEAR[m[1]])continue;
          const a=(CODE[m[1]]=CODE[m[1]]||[]);if(a.indexOf(nm)<0)a.push(nm);}});
    });
  })();
  Object.keys(CODE).forEach(k=>CODE[k].forEach(fn=>
    add(k,{how:'code',card:fn+'()',id:fn,door:'handed over in code, not off a table',pay:''})));

  /* ── 2. can it be ROLLED - onto a rack or out of a fight ──────────────
     `findPool` is the one pool in the game and it is the one place a shop
     rack and a battle find both come out of. These are its clauses, read off
     the ROW rather than off a company, so the answer does not move with who
     happens to be alive when the probe runs. */
  const poolOf=k=>{
    const g=GEAR[k],out=[];
    if(g.unique)out.push('unique: a named thing out of one scene, never rolled and never sold');
    if(g.rarity!=='common'&&!FIND_ODDS.battle[g.rarity]&&!FIND_ODDS.cache[g.rarity])
      out.push('no roll asks for the '+g.rarity+' tier');
    if(g.size&&g.size!=='any')out.push('only while somebody in the company is '+g.size);
    if(g.slot==='main'&&g.rarity==='common')
      out.push('a common main-hand is never handed over (#266)');
    if((g.slot==='armour'&&g.rarity==='epic')||g.spellRange)
      out.push('held back until Blood on the Road is behind you (#236)');
    if(g.slot==='main')out.push('a main-hand must out-hit the weakest weapon in hand, or bring something new');
    return out;
  };
  /* the two clauses that shut a row out of every pool for good, against the
     ones that only narrow it */
  const HARD=/^(unique|no roll asks)/;

  /* ── 2b. WHO GETS FULL VALUE OUT OF IT ────────────────────────────────
     ⛔ THERE IS NO CLASS-GEAR TABLE IN THIS BUILD AND WRITING ONE HERE WOULD BE
     A SECOND ONE. Nothing stops a mage picking up a warclub; what decides who a
     piece of kit is FOR is which field it carries and who the code that reads
     that field pays. So every clause below names the line in the build it is
     read off, and a row that carries none of those fields honestly answers
     "anybody".
       spellRange  unitFrom sums it off all three slots and only castAct and
                   WILL-KICK spend it, so a body with no working gets nothing
       windsCut    subtracted from a working's mood cost, same argument
       rangedDmg   applied only when `main.range` is set, so it is arrows
       meleeHit    added to the blow, so a bow gets nothing out of it
       size        the wrong-size penalty is what a race gate actually is
       forCls      the row names the class itself, which is the easy case     */
  const CLSN=k=>(CLASSES[k]&&CLASSES[k].n)||k;
  const an=w=>('aeiou'.indexOf(String(w).charAt(0).toLowerCase())>=0?'an ':'a ')+w;
  const casters=Object.keys(CLASSES).filter(c=>{
    try{return isCaster(c);}catch(e){return false;}});
  const casterWords=casters.map(CLSN).filter((w,i,a)=>a.indexOf(w)===i).join(' / ');
  const usersOf=k=>{
    const g=GEAR[k],out=[];
    if(g.forCls)out.push({who:CLSN(g.forCls),
      why:'the row names the class: '+(g.bonusD||'a bonus only they get')});
    if(g.spellRange)out.push({who:'a caster · '+casterWords,
      why:'spellRange is spent by a working and by nothing else'});
    if(g.windsCut)out.push({who:'a caster · '+casterWords,
      why:'it cuts what a working costs in mood, so a body with no school saves nothing'});
    if(g.rangedDmg)out.push({who:CLSN('archer')+', with a bow in hand',
      why:'it is added only when the main hand has a range'});
    if(g.meleeHit||g.meleeDmg)out.push({who:'anybody who swings, never an archer',
      why:'it lands on the melee blow, and a bow never makes one'});
    if(g.slot==='main'&&g.range)out.push({who:CLSN('archer'),
      why:'a main hand that shoots is what the trade is'});
    if(g.slot==='main'&&(g.reach||1)>1&&!g.range)out.push({who:CLSN('spear')+'-shaped',
      why:'reach '+(g.reach||1)+', so it holds a lane the way a spear does'});
    if(g.hands===2)out.push({who:'a body that does not want an off hand',
      why:'both hands are on it, so the shield or the quiver goes'});
    if(g.company)out.push({who:'nobody wears it',
      why:'it works from the baggage and takes no trinket slot off anyone'});
    if(g.size&&g.size!=='any'){
      let cls=[];try{cls=(CLS_BY_RACE[g.size]||[])
        .filter((c,i,a)=>a.indexOf(c)===i).map(CLSN);}catch(e){}
      out.push({who:an(g.size+'-sized body')+(cls.length?' · '+cls.join(', '):''),
        why:'wrong-size armour is a real penalty, not a wall'});
    }
    if(g.forRace)out.push({who:'more on a '+g.forRace,
      why:g.bonusD||'a second helping for the right race'});
    const trades=Object.keys(START_GEAR).filter(c=>(START_GEAR[c]||[]).indexOf(k)>=0);
    trades.forEach(c=>out.push({who:'the '+CLSN(c)+' trade arrives holding it',
      why:'START_GEAR'}));
    if(!out.length)out.push({who:'anybody',
      why:'no field on this row asks anything of the body carrying it'});
    return out;
  };

  /* ── 3. the rows ─────────────────────────────────────────────────────── */
  const art={},items=Object.keys(GEAR).map(k=>{
    const g=GEAR[k],eff=[];
    Object.keys(g).forEach(f=>{if(!STRUCT[f])eff.push({k:f,v:g[f]});});
    const ico=ITEM_ICON[k]||'';
    let has=false;
    try{if(ico&&ITEM_ART[ico]){art[ico]=ITEM_ART[ico];has=true;}}catch(e){}
    /* the acts a piece of kit carries in its own right: a trinket's cast, a
       throwable's throw, a consumable's use. Three field names, one shape. */
    const acts=[];
    ['act','throw','use'].forEach(f=>{if(g[f])acts.push(
      Object.assign({_how:f},g[f]));});
    const gates=poolOf(k);
    const price=gearPrice(k),floor=GEAR_FLOOR[g.rarity||'common']||45;
    return {key:k, n:g.n, rarity:g.rarity||'common',
      tier:(RARITY[g.rarity||'common']||{}).n||'?',
      colour:(RARITY[g.rarity||'common']||{}).c||'#c9c2b4',
      slot:g.slot||'', size:g.size||'any', unique:!!g.unique,
      hands:g.hands||1, glyph:g.g||'',
      dmg:g.dmg?[g.dmg[0],g.dmg[1]]:null,
      dmgMean:g.dmg?Math.round((g.dmg[0]+g.dmg[1])/2*10)/10:0,
      am:g.am==null?null:g.am, ft:g.ft==null?null:g.ft,
      reach:g.reach||0, range:g.range||0,
      armour:g.armour||0,
      price:price, floor:floor, floored:price===floor,
      scrap:scrapPay(k), scrapOwn:!!g.scrap,
      ico:ico, art:has,
      eff:eff, acts:acts, d:g.d||'',
      users:usersOf(k),
      sources:SRC[k]||[],
      gates:gates, rollable:!gates.some(x=>HARD.test(x))};
  });

  /* ── 4. a sentence that quotes a figure the row no longer pays ────────
     ⛔ THE PROMISE-VERSUS-PAYMENT SHAPE, ON THE ONE SURFACE THAT STILL TYPES A
     GEAR FIGURE INTO PROSE. `HDA_CUT` rewrote `armour` and `dmg` in place and
     no sentence anywhere moved with them, so a description saying "96 armour"
     is describing a row that stops 27. The test is arithmetic and not a
     judgment: an integer in the sentence which, PUT THROUGH THE CUT, lands on
     what the row actually pays is the pre-cut figure, still on the page.
     ⚡ PROVED BY THE TWO SIDES OF THE SAME PASS: GEAR's own `d` lines quote no
     figures and report zero, the forge's five rows all report. A check that
     only ever returns zero is indistinguishable from a broken one, and this one
     is run over both halves for exactly that reason. */
  const stale=[];
  (function(){
    const C=typeof HDA_CUT!=='undefined'?HDA_CUT:1;
    if(C===1)return;
    const nums=s=>(String(s).match(/\d+/g)||[]).map(Number);
    const scan=(where,key,d)=>{
      const g=GEAR[key];if(!g||!d)return;
      const pairs=[];
      if(g.armour)pairs.push(['armour',g.armour]);
      if(g.dmg){pairs.push(['damage low',g.dmg[0]],['damage high',g.dmg[1]]);}
      const ns=nums(d);
      pairs.forEach(p=>ns.forEach(n=>{
        if(n!==p[1]&&Math.abs(n*C-p[1])<1.5)
          stale.push({where:where,key:key,name:g.n,field:p[0],says:n,pays:p[1]});}));
    };
    try{CRAFT.forEach(c=>scan('the forge at the Old Camp',c.k,c.d));}catch(e){}
    Object.keys(GEAR).forEach(k=>scan('the row’s own description',k,GEAR[k].d));
  })();

  /* ── 5. what was drawn and hangs on nothing, and the reverse ─────────── */
  const icoNoRow=Object.keys(ITEM_ICON).filter(k=>!GEAR[k]);
  icoNoRow.forEach(k=>{const a=ITEM_ICON[k];
    try{if(ITEM_ART[a])art[a]=ITEM_ART[a];}catch(e){}});

  /* ⛔ EVERY FIGURE ABOVE IS POST-CUT AND THAT IS THE ONLY HONEST READING.
     `HDA_CUT` rewrites `GEAR[k].armour` and `GEAR[k].dmg` IN PLACE at boot, so
     the ogre scale authored at 104 is a 30 by the time anything reads it, and
     `gearPrice()` charges off the cut dice exactly as this probe reads them.
     The dex shows what the board shows, which is the foe dex's own rule; the
     tool prints the dial beside the figures so nobody reads a 30 as an
     authored number. ⚠ A `d` line that says "27-40 dmg" is the AUTHORED figure
     and will disagree - that is a real defect in the prose, and the tool
     showing both is how it gets found. */
  return {built:new Date().toISOString().slice(0,10),
    hdaCut:typeof HDA_CUT!=='undefined'?HDA_CUT:1,
    items:items, art:art, stale:stale,
    /* ⛔ THE PRICE OF A DRAFT IS PRICED BY THE BUILD'S OWN FUNCTION, SHIPPED
       VERBATIM. The tool lets a new artifact be sketched, and a second copy of
       the price model living in the tool is precisely the drift this file
       exists to report: `gearPrice` is handed over as source and run against a
       one-row shim, so a weight moving in the build moves the draft's price on
       the next regenerate and nobody has to remember. */
    priceFn:gearPrice.toString(),
    classes:Object.keys(CLASSES).map(k=>({k:k,n:CLASSES[k].n,
      sig:CLASSES[k].sig||'',caster:(function(){try{return !!isCaster(k);}catch(e){return false;}})(),
      start:START_GEAR[k]||[]})),
    clsByRace:(typeof CLS_BY_RACE!=='undefined')?CLS_BY_RACE:{},
    rarity:RARITY, floors:GEAR_FLOOR, scrapTable:SCRAP,
    findOdds:FIND_ODDS, findSlot:FIND_SLOT, mark:GEAR_MARK,
    startGear:START_GEAR,
    orphans:{
      icoNoRow:icoNoRow.map(k=>({key:k,ico:ITEM_ICON[k],
        art:(function(){try{return !!ITEM_ART[ITEM_ICON[k]];}catch(e){return false;}})()})),
      rowNoIco:Object.keys(GEAR).filter(k=>!ITEM_ICON[k]),
      icoNoArt:Object.keys(ITEM_ICON).filter(k=>{
        try{return !ITEM_ART[ITEM_ICON[k]];}catch(e){return true;}})},
    lootKinds:Object.keys(LOOT).length,
    deck:{road:Object.keys(EVENTS).length,fire:CAMPS.length,vignette:VIGNETTES.length}};
})()
