# ============================================================================
# embed.ps1 - put a built art block where the game loads it from.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File art\embed.ps1 [all|art_data|j_pack]
#
# Reads art\out\<name>.js (written by build_assets.ps1 / build_j_pack.py) and
# writes art\embed\<name>.js, which is TRACKED and is what
# prototype\grimtoll_slice.html loads with a script tag.
#
# ⛔ #235 - THIS REPLACES "INJECT INTO THE PROTOTYPE", AND THAT IS THE POINT.
# Both injectors used to read the whole 30 MB prototype and write it whole back,
# and both carried the same warning: "this is exactly the shape that erases a
# parallel session's work. Ask first." They wrote 27 MB of base64 into the file
# every session had open. Now each block is its own file, two desks writing two
# different blocks cannot collide at all, and the prototype is not touched - so
# the claim gate those scripts needed is gone with the danger it guarded.
#
# ⚠ LF, NO BOM, AND THE HEADER IS BYTE-FOR-BYTE STABLE. These are 13 MB tracked
# files: a newline convention that flips, or a header that reads differently
# between two writers, is a 13 MB diff that says nothing. Change the header here
# and nowhere else.
#
# ---------------------------------------------------------------------------
# KEEP THIS FILE PURE ASCII, same as deploy.ps1 and build_site.ps1: PowerShell
# 5.1 reads a .ps1 as ANSI and this repo's path is Cyrillic.
# ---------------------------------------------------------------------------
param([string] $Which = 'all')

$ErrorActionPreference = 'Stop'
$root  = Split-Path $PSScriptRoot -Parent
$outD  = Join-Path $PSScriptRoot 'out'
$embD  = Join-Path $PSScriptRoot 'embed'

$blocks = @{
  'art_data' = @{ mark = 'ART_DATA'; who = 'art/build_assets.ps1 + art/inject.ps1' }
  'j_pack'   = @{ mark = 'J_PACK';   who = 'art/build_j_pack.py + art/inject_j_pack.ps1' }
}

$want = if ($Which -eq 'all') { @('art_data', 'j_pack') } else { @($Which) }
foreach ($n in $want) {
  if (-not $blocks.ContainsKey($n)) { throw "unknown block '$n'. Use all, art_data or j_pack." }
}
if (-not (Test-Path -LiteralPath $embD)) { New-Item -ItemType Directory -Force -Path $embD | Out-Null }

foreach ($n in $want) {
  $src = Join-Path $outD ($n + '.js')
  if (-not (Test-Path -LiteralPath $src)) {
    if ($Which -eq 'all') { Write-Warning "art\out\$n.js is missing - skipped. Build it first."; continue }
    throw "art\out\$n.js not found. Run build_assets.ps1 (art_data) or build_j_pack.py (j_pack) first."
  }
  $mark = $blocks[$n].mark
  $who  = $blocks[$n].who
  $body = [System.IO.File]::ReadAllText($src) -replace "`r`n", "`n"
  $head = @(
    "/* GENERATED by $who - do not hand-edit.",
    "   #235: this used to sit inside prototype/grimtoll_slice.html between the",
    "   __${mark}__ markers. It is a top-level CLASSIC script, so every ``const`` below",
    "   is a global lexical binding the main script can read - which is the whole",
    "   reason this works without touching a single line of game code.",
    "   tools/build_site.ps1 pours it back inline for the page that ships.",
    "   The marker names are written without their slashes on purpose: a nested",
    "   comment terminator would close this comment 13 MB early. */"
  ) -join "`n"
  $text = $head + "`n" + $body.Trim("`n") + "`n"
  $dst  = Join-Path $embD ($n + '.js')
  [System.IO.File]::WriteAllText($dst, $text, (New-Object System.Text.UTF8Encoding($false)))
  "embedded: art\embed\$n.js  ({0:N2} MB)" -f ($text.Length / 1MB)
}

"the prototype loads these directly. Nothing else to run; tools\build_site.ps1"
"pours them inline for the page that ships."
