# Compresses the approved WAV pack and emits it as data: URIs, so the PUBLISHED
# single-file build has sound. Local play is unaffected: with `audio/` beside the
# page the game keeps reading the 44.1k masters.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File audio\build_audio.ps1
#   powershell -NoProfile -ExecutionPolicy Bypass -File audio\build_audio.ps1 -Inject
#   ... -Codec opus -Bitrate 48k -Inject
#   ... -Only main_menu            # one track, for testing the pipeline
#
# WHY THIS EXISTS: 82MB of 44.1k WAV cannot travel inside an HTML file, so from
# 8f.70 until now the shared build was completely silent - no music and no SFX.
# Compressed, the same twelve cues are ~3.7MB, which a published artifact does
# carry (measured: a 7.6MB page publishes, and data: audio survives the CSP).
#
# CODEC: aac (.m4a) by default, ON PURPOSE. Opus is the better codec per byte,
# but Opus-in-WebM needs iOS 17.4 or newer and AAC plays on every iPhone ever
# made. A playtester on an old phone hearing nothing is the exact bug being
# fixed here, so compatibility outranks the last few percent of quality.
#
# ---------------------------------------------------------------------------
# KEEP THIS FILE PURE ASCII. PowerShell 5.1 reads a .ps1 as ANSI, and the repo
# path contains Cyrillic ("Google <disk>"): a literal non-ASCII character here
# comes back as mojibake at runtime. Every path is derived from $PSScriptRoot
# instead of being written out. The same trap already bit tools/serve.ps1, and
# art/build_assets.ps1 still emits a mojibake em dash into the prototype.
# ---------------------------------------------------------------------------
param(
  [ValidateSet('aac','opus')] [string] $Codec   = 'aac',
  [string] $Bitrate = '64k',
  [string] $Only    = '',
  [switch] $Inject
)

$ErrorActionPreference = 'Stop'
$audio = $PSScriptRoot
$root  = Split-Path $audio -Parent
$outJs = Join-Path $audio 'out\audio_data.js'

# ---- find ffmpeg ------------------------------------------------------------
$ff = (Get-Command ffmpeg -ErrorAction SilentlyContinue).Source
if (-not $ff) {
  $ff = (Get-ChildItem (Join-Path $env:LOCALAPPDATA 'Microsoft\WinGet\Packages') `
          -Recurse -Filter ffmpeg.exe -ErrorAction SilentlyContinue |
         Select-Object -First 1).FullName
}
if (-not $ff) { throw "ffmpeg not found. Install it: winget install Gyan.FFmpeg" }

# container, MIME and encoder flags per codec
if ($Codec -eq 'opus') {
  $ext = 'webm'; $mime = 'audio/webm'
  $enc = @('-c:a','libopus','-b:a',$Bitrate,'-vbr','constrained','-application','audio','-ac','2')
} else {
  $ext = 'm4a';  $mime = 'audio/mp4'
  $enc = @('-c:a','aac','-b:a',$Bitrate,'-ac','2','-movflags','+faststart')
}

$work = Join-Path $audio "web\$Codec"
New-Item -ItemType Directory -Force -Path $work, (Split-Path $outJs -Parent) | Out-Null

# ---- encode, then base64 ----------------------------------------------------
# ONE FLAT TABLE KEYED BY FILENAME, not by folder. The eleven cue names are
# unique across music/ and sfx/, and the game already asks for them by bare
# name, so a flat table is what the call sites want.
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('/*__AUDIO_DATA__*/')
[void]$sb.AppendLine("/* GENERATED by audio/build_audio.ps1 - do not hand-edit.")
[void]$sb.AppendLine("   The approved pack at $Codec $Bitrate, as data: URIs, so the published")
[void]$sb.AppendLine('   single-file build has sound. Empty table = the game falls back to')
[void]$sb.AppendLine('   reading ../audio/*.wav, which is what a local dev server serves. */')
[void]$sb.Append('const AUDIO_EMBED={')

$rows = @(); $first = $true; $total = 0
foreach ($d in 'music','sfx') {
  Get-ChildItem (Join-Path $audio "$d\*.wav") | ForEach-Object {
    $n = $_.BaseName
    if ($Only -and $n -ne $Only) { return }
    $dst = Join-Path $work "$n.$ext"
    & $ff -y -hide_banner -loglevel error -i $_.FullName @enc $dst
    if ($LASTEXITCODE -ne 0) { throw "ffmpeg failed on $n" }

    $b64 = [Convert]::ToBase64String([System.IO.File]::ReadAllBytes($dst))
    if (-not $first) { [void]$sb.Append(',') }
    [void]$sb.Append("`n$n" + ':"data:' + $mime + ';base64,' + $b64 + '"')
    $first = $false; $total += $b64.Length

    $rows += [pscustomobject]@{
      cue = $n; folder = $d
      wavKB = [int]($_.Length/1KB); outKB = [int]((Get-Item $dst).Length/1KB)
    }
  }
}
[void]$sb.AppendLine('};')
[void]$sb.Append('/*__END_AUDIO_DATA__*/')

# UTF8 with NO BOM: the prototype is read and rewritten as utf8 and a BOM
# landing mid-file would be pasted straight into the middle of a script block.
[System.IO.File]::WriteAllText($outJs, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))

$rows | Format-Table -AutoSize
"codec {0} {1} | {2} cues | base64 {3} MB -> out\audio_data.js" -f `
  $Codec, $Bitrate, $rows.Count, [Math]::Round($total/1MB,2)

# ---- inject ------------------------------------------------------------------
# Idempotent, and identical in shape to art/inject.ps1 so there is one habit to
# remember rather than two.
if ($Inject) {
  $html = Join-Path $root 'prototype\grimtoll_slice.html'
  $src  = Get-Content $html -Raw -Encoding utf8
  $blk  = Get-Content $outJs -Raw -Encoding utf8
  $s = '/*__AUDIO_DATA__*/'; $e = '/*__END_AUDIO_DATA__*/'
  if ($src -notmatch [regex]::Escape($s)) { throw "marker $s not found in the prototype" }
  if ($src -match [regex]::Escape($e)) {
    $pat = [regex]::Escape($s) + '[\s\S]*?' + [regex]::Escape($e)
    $src = [regex]::Replace($src, $pat, { param($m) $blk })
  } else {
    $src = $src -replace [regex]::Escape($s), $blk
  }
  Set-Content -Path $html -Value $src -Encoding utf8 -NoNewline
  "injected. prototype is now {0} MB" -f [Math]::Round((Get-Item $html).Length/1MB,2)
}
